sudo: required
dist: trusty
language: python
 - "3.5"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cpanminus texlive-xetex libxml-libxslt-perl libparse-recdescent-perl

script:
 - export LMH_ROOT_DIR=`pwd`
 - export PATH=`pwd`/bin:$PATH
 - lmh setup --install LaTeXML LaTeXMLs sTeX
