sudo: required
dist: trusty
language: python
 - "3.5"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cpanminus texlive-full libxml-libxslt-perl libparse-recdescent-perl openjdk-7-jre libjson-xs-perl libarchive-zip-perl libimage-size-perl

install:
 - ssh-keyscan -H gl.mathhub.info >> ~/.ssh/known_hosts
 - sudo -i pip3 install lxml

script:
 - export LMH_ROOT_DIR=`pwd`
 - export PATH=`pwd`/bin:$PATH
 - lmh setup --install
 - testHello.sh
